version: '3'

services:
  identity:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password