version: '3.8'

services:
  spring-app:
    build:
      context: .  # Path to your Spring Boot application's directory
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/contact_db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
  mysqldb:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: contact_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data